// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const rawUrl = import.meta.env.VITE_SUPABASE_URL;
const rawKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Check if the URL is valid. If not, use a placeholder to prevent crashing on load.
const isValidUrl = (url: string | undefined): url is string => {
  if (!url || url === 'YOUR_SUPABASE_URL' || url === '') return false;
  try {
    new URL(url);
    return true;
  } catch {
    return false;
  }
};

const SUPABASE_URL = isValidUrl(rawUrl) ? rawUrl.replace(/\/$/, '') : 'https://placeholder-project.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = (rawKey && rawKey !== 'YOUR_SUPABASE_PUBLISHABLE_KEY' && rawKey !== '') 
  ? rawKey 
  : 'placeholder-key';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});

if (!isValidUrl(rawUrl)) {
  console.warn("Supabase URL is missing or invalid. Using a placeholder client. Please set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your environment variables if you need Supabase features.");
}
